"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CHANNEL_PROPERTIES = void 0;
const NAME_1 = require("./NAME");
const ID_1 = require("./ID");
const TYPE_1 = require("./TYPE");
const PERMISSIONS_1 = require("./PERMISSIONS");
class CHANNEL_PROPERTIES {
}
CHANNEL_PROPERTIES.NAME = NAME_1.NAME;
CHANNEL_PROPERTIES.ID = ID_1.ID;
CHANNEL_PROPERTIES.MAX_PRIVATE_CHANNELS = 1000;
CHANNEL_PROPERTIES.MAX_GROUP_CHANNELS = 1000;
CHANNEL_PROPERTIES.MAX_SERVER_CHANNELS = 1000;
CHANNEL_PROPERTIES.TYPE = TYPE_1.TYPE;
CHANNEL_PROPERTIES.PERMISSIONS = PERMISSIONS_1.PERMISSIONS;
exports.CHANNEL_PROPERTIES = CHANNEL_PROPERTIES;
