"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SERVER_PROPERTIES = void 0;
const MESSAGE_1 = require("./MESSAGE");
const ID_1 = require("./ID");
const NAME_1 = require("./NAME");
const PERMISSIONS_1 = require("./PERMISSIONS");
class SERVER_PROPERTIES {
}
SERVER_PROPERTIES.MESSAGE = MESSAGE_1.MESSAGE;
SERVER_PROPERTIES.ID = ID_1.ID;
SERVER_PROPERTIES.NAME = NAME_1.NAME;
SERVER_PROPERTIES.PERMISSIONS = PERMISSIONS_1.PERMISSIONS;
SERVER_PROPERTIES.MIN_CHANNELS = 1;
SERVER_PROPERTIES.MAX_CHANNELS = 50;
exports.SERVER_PROPERTIES = SERVER_PROPERTIES;
